//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.42000
//


/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="PrimeNumberWebServicePortBinding", Namespace="http://PrimeNumberWebService/")]
public partial class PrimeNumberWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback helloOperationCompleted;
    
    private System.Threading.SendOrPostCallback numberOfPrimeNumbersInRangeOperationCompleted;
    
    /// CodeRemarks
    public PrimeNumberWebService() {
        this.Url = "http://localhost:8080/PrimeNumberWebApplication/PrimeNumberWebService";
    }
    
    /// CodeRemarks
    public event helloCompletedEventHandler helloCompleted;
    
    /// CodeRemarks
    public event numberOfPrimeNumbersInRangeCompletedEventHandler numberOfPrimeNumbersInRangeCompleted;
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://PrimeNumberWebService/", ResponseNamespace="http://PrimeNumberWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hello([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string name) {
        object[] results = this.Invoke("hello", new object[] {
                    name});
        return ((string)(results[0]));
    }
    
    /// CodeRemarks
    public void helloAsync(string name) {
        this.helloAsync(name, null);
    }
    
    /// CodeRemarks
    public void helloAsync(string name, object userState) {
        if ((this.helloOperationCompleted == null)) {
            this.helloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloOperationCompleted);
        }
        this.InvokeAsync("hello", new object[] {
                    name}, this.helloOperationCompleted, userState);
    }
    
    private void OnhelloOperationCompleted(object arg) {
        if ((this.helloCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.helloCompleted(this, new helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://PrimeNumberWebService/", ResponseNamespace="http://PrimeNumberWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numberOfPrimeNumbersInRange([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int range) {
        object[] results = this.Invoke("numberOfPrimeNumbersInRange", new object[] {
                    range});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void numberOfPrimeNumbersInRangeAsync(int range) {
        this.numberOfPrimeNumbersInRangeAsync(range, null);
    }
    
    /// CodeRemarks
    public void numberOfPrimeNumbersInRangeAsync(int range, object userState) {
        if ((this.numberOfPrimeNumbersInRangeOperationCompleted == null)) {
            this.numberOfPrimeNumbersInRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnumberOfPrimeNumbersInRangeOperationCompleted);
        }
        this.InvokeAsync("numberOfPrimeNumbersInRange", new object[] {
                    range}, this.numberOfPrimeNumbersInRangeOperationCompleted, userState);
    }
    
    private void OnnumberOfPrimeNumbersInRangeOperationCompleted(object arg) {
        if ((this.numberOfPrimeNumbersInRangeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.numberOfPrimeNumbersInRangeCompleted(this, new numberOfPrimeNumbersInRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void helloCompletedEventHandler(object sender, helloCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void numberOfPrimeNumbersInRangeCompletedEventHandler(object sender, numberOfPrimeNumbersInRangeCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class numberOfPrimeNumbersInRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal numberOfPrimeNumbersInRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
